set CMDBDriver=oracle.jdbc.driver.OracleDriver
set CMDBDURL=jdbc:oracle:thin:@localhost:1521/orcl
set CMDBUser=ncbadb
set CMDBPassword=ncba123
#set CMDBPassword=6f99668b94326256
set CMDBPoolSize=10
set CMDBValidationQuery= "select systimestamp from dual"
set CMDBTestConnectionOnCheckout=false
set CoreDBSChema=ncbadb
set ChannelDBSchema=ncbacib
set CMDBCheckoutTimeout=5000
set CORE_SERVICES_MP_REST_URL=http://localhost:8081
set BATCH_CORE_SERVICES_MP_REST_URL=http://localhost:8080
#set PESLINK_CORE_SERVICES_MP_REST_URL=http://192.168.90.101:1700
set PESLINK_CORE_SERVICES_MP_REST_URL=https://trinity.cbaloop.com
set MOBILE_MONEY_CORE_SERVICES_MP_REST_URL=https://205.205.210.139:7024
set MOBILE_AIRTIME_CORE_SERVICES_MP_REST_URL=https://205.205.210.62
java -jar target\NLSPostingServices-bootable.jar  -Djboss.bind.address=0.0.0.0
#set com.nls.core.CoreServices/generateReference/Timeout/enabled=true
#set com.nls.core.CoreServices/generateReference/Timeout/unit=MILLIS
#set com.nls.core.CoreServices/generateReference/Timeout/value =2
#set com.nls.core.CoreServices/LockingTransactions/Timeout/enabled=true
#set com.nls.core.CoreServices/LockingTransactions/Timeout/unit=MILLIS
#set com.nls.core.CoreServices/LockingTransactions/Timeout/value =25
#set com.nls.core.CoreServices/TransDuplicateCheck/Timeout/enabled=true
#set com.nls.core.CoreServices/TransDuplicateCheck/Timeout/unit=MILLIS
#set com.nls.core.CoreServices/TransDuplicateCheck/Timeout/value =20
#set com.nls.core.CoreServices/ValidateTransactions/Timeout/enabled=true
#set com.nls.core.CoreServices/ValidateTransactions/Timeout/unit=MILLIS
#set com.nls.core.CoreServices/ValidateTransactions/Timeout/value =80
#set com.nls.core.CoreServices/OFSFormatter/Timeout/enabled=true
#set com.nls.core.CoreServices/OFSFormatter/Timeout/unit=MILLIS
#set com.nls.core.CoreServices/OFSFormatter/Timeout/value =40
#set com.nls.core.CoreServices/QueueService/Timeout/enabled=true
#set com.nls.core.CoreServices/QueueService/Timeout/unit=MILLIS
#set com.nls.core.CoreServices/QueueService/Timeout/value =30
#set com.nls.core.CoreServices/PersistUniqueData/Timeout/enabled=true
#set com.nls.core.CoreServices/PersistUniqueData/Timeout/unit=MILLIS
#set com.nls.core.CoreServices/PersistUniqueData/Timeout/value =20
#set com.nls.core.CoreServices/ReleaseLock/Timeout/enabled=true
#set com.nls.core.CoreServices/ReleaseLock/Timeout/unit=MILLIS
#set com.nls.core.CoreServices/ReleaseLock/Timeout/value =20
#set com.nls.posting.InternalTransfer/getInternalTransferDetails/Timeout/enabled=true
#set com.nls.posting.InternalTransfer/getInternalTransferDetails/Timeout/unit=MILLIS
#set com.nls.posting.InternalTransfer/getInternalTransferDetails/Timeout/value =5000