set CMDBDriver=oracle.jdbc.driver.OracleDriver
set CMDBDURL=jdbc:oracle:thin:@localhost:1521/orcl
set CMDBUser=ncbadb
set CMDBPassword=ncba123
#set CMDBPassword=6f99668b94326256
set CMDBPoolSize=10
set CMDBValidationQuery= "select systimestamp from dual"
set CMDBTestConnectionOnCheckout=false
set CoreDBSChema=ncbadb
set ChannelDBSchema=ncbacib
set CMDBCheckoutTimeout=5000
set CORE_SERVICES_MP_REST_URL=http://localhost:8081
set BATCH_CORE_SERVICES_MP_REST_URL=http://localhost:8080
#set PESLINK_CORE_SERVICES_MP_REST_URL=http://192.168.90.101:1700
set PESLINK_CORE_SERVICES_MP_REST_URL=https://trinity.cbaloop.com
set MOBILE_MONEY_CORE_SERVICES_MP_REST_URL=https://205.205.210.139:7024
set MOBILE_AIRTIME_CORE_SERVICES_MP_REST_URL=https://205.205.210.62
java -jar target\NLSPostingServices-bootable.jar  -Djboss.bind.address=0.0.0.0
#set CORE_SERVICES/mp-rest/readTimeout=20
#set CORE_SERVICES/mp-rest/connectTimeout=20
set com.nls.core.CoreServices/mp-rest/readTimeout=10 
set com.nls.core.CoreServices/mp-rest/connectTimeout=10
#set com.nls.posting.InternalTransfer/getInternalTransferDetails/Timeout/enabled=true
#set com.nls.posting.InternalTransfer/getInternalTransferDetails/Timeout/unit=MILLIS
#set com.nls.posting.InternalTransfer/getInternalTransferDetails/Timeout/value =5000