package com.nls.posting;

public enum ResponseStatus {
  UNIQUE_DATA("UNIQUE_DATA"),
  FAILED("FAILED"),
  SUCCESS("SUCCESS"),
  PENDING("PENDING"),
  DUPLICATE_DATA("DUPLICATE_DATA"),
  NO_VALID_LOCKS_FOUND("NO_VALID_LOCKS_FOUND"),
  SERVICE_MAPPING_NOT_FOUND("SERVICE_MAPPING_NOT_FOUND"),
  FORMATTED_SUCCESSFULLY("FORMATTED_SUCCESSFULLY"),
  LOCK_RELEASED_SUCCESSFULLY("LOCK_RELEASED_SUCCESSFULLY"),
  UNIQUE_REFERENCE_GENERATED_FAILED("UNIQUE_REFERENCE_GENERATED_FAILED"),
  TRANSACTION_ALREADY_LOCKED("TRANSACTION_ALREADY_LOCKED"),
  LOCKING_TRANSACTION_UNSUCCESSFUL("LOCKING_TRANSACTION_UNSUCCESSFUL"),
  TRANSACTION_ALREADY_PROCESSED("TRANSACTION_ALREADY_PROCESSED"),
  VALIDATION_TRANSACTION_UNSUCCESSFUL("VALIDATION_TRANSACTION_UNSUCCESSFUL"),
  VALIDATING_FINANCIAL_TRANSACTION_UNSUCCESSFUL("VALIDATING_FINANCIAL_TRANSACTION_UNSUCCESSFUL"),
  OFS_FORMATTING_UNSUCCESSFUL("OFS_FORMATTING_UNSUCCESSFUL"),
  QUEUING_TRANSACTIONS_FAILED("QUEUING_TRANSACTIONS_FAILED"),
  DUPLICATE_DATA_FOUND("DUPLICATE_DATA_FOUND"),
  TRANSACTION_DETAIL_LOGGING_UNSUCCESSFUL("TRANSACTION_DETAIL_LOGGING_UNSUCCESSFUL"),
  LOCK_EXISTS("LOCK_EXISTS"),
  RELEASING_LOCK_UNSUCCESSFUL("RELEASING_LOCK_UNSUCCESSFUL"),
  ACCOUNT("ACCOUNT"),
  TRANSACTION("TRANSACTION"),
  SUCCESSFUL("SUCCESSFUL"),
  LOCK_PERIOD("60"),
  LOCK_FUNDS("true"),
  BIC_NOT_FOUND("INVALID_BIC_CODE"),
  CUSTOM_VALIDATION_UNSUCCESSFUL("CUSTOM_VALIDATION_UNSUCCESSFUL"),
  INVALID_BENEFICIARY_ACCOUNT("INVALID_BENEFICIARY_ACCOUNT"),
  CHARGE_NOT_FOUND("CHARGE_NOT_FOUND"),
  Y("Y"),
  N("N"),
  TRANS_COUNT_MISMATCH("Transaction Counts are not Matching !"),
  DUPLICATE_BATCH_REFERENCE("Duplicate Batch Reference!"),
  RTGS("RTGS"),
  PESALINK("PesaLink"),
  EFT("EFT"),
  MOBILE_WALLET("MobileMoneyTransfer"),
  INVALID_TRANSACTION_TYPE("INVALID_TRANSACTION_TYPE"),
  SACCO("SaccoTransfer"),
  CHANNEL("CIB"),
  TRANSACTION_ABORT("MASTER_TRANSACTION_FAILED"),
  TRANS_AMOUNT_MISMATCH("Transaction Amounts Mismatch !"),
  ACCOUNT_NOT_FOUND("ACCOUNT_NUMBER_NOT_FOUND");

  private String value;

  ResponseStatus(String value) {
    this.setValue(value);
  }

  public String getValue() {
    return this.value;
  }

  public void setValue(String value) {
    this.value = value;
  }
}
